[package]
name = "zero_g"
version = "0.1.0"
edition = "2021"

[lib]
name = "zero_g"
path = "src/lib.rs"

[dependencies]
plotters = { version = "0.3.0" }
halo2_proofs = { version = "0.3.0", features = ["dev-graph"] }
num-bigint = "0.4.3"
hdf5 = "0.8.1"
ndarray = "0.15.6"
