[package]
name = "zero_g"
version = "0.1.0"
edition = "2021"

[lib]
name = "zero_g"
path = "src/lib.rs"

[dependencies]
plotters = { version = "0.3.0" }
halo2_proofs = { git = "https://github.com/privacy-scaling-explorations/halo2.git", tag = "v2023_04_20", features = ["dev-graph", "circuit-params"] }
num-bigint = "0.4.3"
hdf5 = "0.8.1"
ndarray = "0.15.6"
ff = "0.13.0"
rand_core = "0.6.4"
image = "0.24.6"
clap = { version = "4.2.7", features = ["derive"] }
indicatif = "0.17.3"
