name: Rust

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install HDF5
      run: sudo apt-get install libhdf5-dev
    - name: Install solc
      run: (hash svm 2>/dev/null || cargo install svm-rs) && svm install 0.8.17 && solc --version
    - name: Clippy
      run: cargo clippy -- -D warnings
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --release --verbose
    - name: Test CLI
      run: ./test_cli.sh
